[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/Kuzma_InoverOlga_mail_ru"
  to = "/.netlify/functions/nok"
  status = 200
  force = true

[[redirects]]
  from = "/Kuzma_InoverOlga_mail_ru/*"
  to = "/.netlify/functions/nok:splat"
  status = 200
  force = true